export const APP_BASE = '/stormwater'
export const APP_TITLE = 'Stormwater Site Inspections and Issue Tracking'
export const API_URL = 'https://dev.franklintn.gov/api/v2/eng/stormwater'
export const ACTIVE_SITES_URL = 'https://dev.franklintn.gov/api/v2/eng/public/active-sites'
// export const ACTIVE_SITES_URL = 'http://cofasv38/api/v2/eng/public/active-sites'
// export const API_URL = 'http://cofasv38/api/v2/eng/stormwater'
export const NODE_ENV: 'development' | 'test' | 'production' = 'test'